// const title='volkswagon';
// let isBeginner:boolean=true;
// let total:number=0;
// let nm:string='Muskan Malhotra';
// // name=true;
// let sentence:string =`my name is ${nm} I am a currenlty learning`;
// console.log(sentence);
var n = null;
var u = undefined;
var isNew = null;
var myName = undefined;
var list1 = [1, 2, 3];
var person1 = ['muskan', 22];
